#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
currDir=$PWD
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0 > /dev/null 2>&1
rm -r processor*
cd constant
#rm -r bedOfSpheres
#rm -r fluid
rm cell*
cd polyMesh
rm -r sets
ls *|grep -v blockMeshDict|xargs rm -r
cd $currDir
rm log.*
rm -r bedOfSpheres
rm -r VTK
rm -r MeshLog
#cd system
#rm -r fluid bedOfSpheres
rm -r constant/fluid/polyMesh
rm -r constant/bedOfSpheres/polyMesh

# ----------------------------------------------------------------- end-of-file
