#!/bin/bash

foamLog log.chtMultiRegionFoam >/dev/null

gnuplot -persist > /dev/null 2>&1 << EOF
        set logscale y
        set title "Residual vs. Iteration"
        set xlabel "Iteration"
        set ylabel "Residual"
        plot "logs/Ux_0" with lines,\
                "logs/Uy_0" with lines,\
                "logs/Uz_0" with lines,\
                "logs/p_rgh_0" with lines,\
                "logs/h_0" with lines
        pause 2
        reread
EOF

# ----------------------------------------------------------------- end-of-file
