#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
currDir=$PWD
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./AllrunMesh

./LayersFluid

./LayersSpheres


# ----------------------------------------------------------------- end-of-file
