#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

currDir=$PWD

# Source tutorial clean functions
#. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/*.eMesh > /dev/null 2>&1
rm -f constant/polyMesh/boundary

#cleanCase
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -rf 0/solidSphere
rm -rf 0/fluid
rm -f 0/cellToRegion
rm -rf constant/solidSphere/polyMesh
rm -rf constant/fluid/polyMesh
rm -rf meshLogFiles

cd constant/polyMesh
ls *|grep -v blockMeshDict|xargs rm -r
cd $currDir
# ----------------------------------------------------------------- end-of-file
