#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

currDir=$PWD

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# remove fluid fields from solid regions (important for post-processing)
for i in solidSphere
do
   rm -f 0*/$i/{epsilon,k,U,p_rgh}
done

rm -r 0/solidSphere

rm -r 0/fluid

cp -r 0.org/solidSphere 0/

cp -r 0.org/fluid 0/

## Run on single processor
#runApplication `getApplication`

## Decompose
runApplication decomposePar -allRegions

## Run
runParallel `getApplication` 8

## Reconstruct
runApplication reconstructPar -allRegions

# ----------------------------------------------------------------- end-of-file
